### ISSUE TITLE
Specification link redirects not working?

### ISSUE THREAD

**Issue by jamsden** [OSLC/oslc-site-hugo#222] opened 2018-11-08 13:32 UTC
Shouldn't http://open-services.net/bin/view/Main/QmSpecificationV2 redirect to http://archive.open-services.net/bin/view/Main/QmSpecificationV2

**Comment by berezovskyi** [comment] 2018-11-09 23:02
It does. You just have to click on the Archive link because the redirection is not automatic.

**Comment by gabrielfdac** [comment] 2018-11-12 15:10
If that is an important link or often used one we could create a permanent redirect on nginx

**Comment by berezovskyi** [comment] 2019-05-21 09:13
Is it a duplicate of #225?

**Comment by berezovskyi** [comment] 2019-06-27 18:36
The redirect works now

**Closed by berezovskyi** 2019-06-27 18:36 UTC
Labels: duplicate
