### ISSUE TITLE
OSLC Developer Guide links are broken

### ISSUE THREAD

**Issue by jamsden** [OSLC/oslc-site-hugo#223] opened 2018-11-09 18:31 UTC
http://oslc.github.io/developing-oslc-applications/ has a series of tutorials and developer guides that have many links to open-services.net URLs that are now in the archive. I wonder if it would be possible to have these links redirect to the archive so they aren't broken.

In particular, it is most unfortunate that https://archive.open-services.net/resources/tutorials/oslc-primer/index.html got lost in the transition as this is exactly the overview people seem to be asking for.

**Comment by berezovskyi** [comment] 2018-11-09 23:07
So, the links are redirected but not automatically. You need to click on a link on a 404 page. The problem is that it's a blanket redirect, not a set of smart rules. I.e. you will see a button to try the archive even if you navigate to https://open-services.net/qwertyuiop%C3%A5%C3%A4%C3%B6lkjhgfdsa

**Comment by berezovskyi** [comment] 2019-05-21 09:13
Fixed in #243

**Closed by berezovskyi** 2019-05-21 09:13 UTC
